### ISSUE TITLE
Error: zero-length inputs cannot be mixed with those of non-zero length

### ISSUE THREAD

**Issue by liwencong1995** [beanumber/nyc311#15] opened 2016-10-04 19:42 UTC
I was able to simply fix this error by using `download.file` instead of `smart_download`. However, I am not sure whether I should get rid of smart_download from my `etl_extract` function. 
Maybe `apply` is not working properly?

```
> smart_download(obj, src = valid_months$src, 
+                    new_filenames = basename(valid_months$lcl), 
+                    method = "curl", quiet = FALSE)
```

Error Message:

```
Error in mapply(utils::download.file, src[missing], lcl[missing], ... = ...) : 
  zero-length inputs cannot be mixed with those of non-zero length
```

The command below works fine, but we have to add a for loop in order to download data for all the months:

```
download.file(valid_months$src[[1]], valid_months$lcl[[1]])
```

**Comment by beanumber** [comment] 2016-10-04 19:49
OK, but have you checked this on other platforms? Remember that
smart_download() was written to create problems caused by download.file().

**Comment by liwencong1995** [comment] 2016-10-04 19:56
Could you explain what are other platforms that I should check?

**Comment by beanumber** [comment] 2016-10-04 20:00
Windows, Mac OS X, and Linux. The Travis-CI check is running Ubuntu Linux, so as long as you write a test function, it will check it for you.

**Comment by liwencong1995** [comment] 2016-10-04 22:13
@beanumber Will do.

**Comment by beanumber** [comment] 2016-11-07 18:41
I have updated `etl::smart_download()` to use the `downloader::download()` function instead of `download.file()`. This is supposed to smooth out these issues. Can you update your `etl` to version 0.3.4 and see if it fixes your issue?

**Comment by liwencong1995** [comment] 2016-11-08 21:54
I have updated my `etl` package, and I tried the following code:

```
calls <- etl("nyc311", dir = "/Users/Priscilla/Desktop/nyc311")
call %>%
  etl_extract(years = 2010:2011, months = 1:3, num_calls = 100)
```

I got the following WARNING, and nothing was downloaded. The `raw` folder is empty.

```
Warning messages:
1: In download.file(url, method = method, ...) :
  formal argument "method" matched by multiple actual arguments
2: In download.file(url, method = method, ...) :
  formal argument "method" matched by multiple actual arguments
```

So I tried this:

```
years <- 2011
months <- 2
num_calls = 100
valid_months <- mutate_(valid_months, src = ~paste0(base_url, 
                  "?$where=created_date%20between%20'", month_begin,
                  "'%20and%20'", month_end, "'&$limit=", format(num_calls, scientific = FALSE)))
  dir <- attr(obj, "raw_dir")
  valid_months <- mutate(valid_months, lcl = paste0(dir, "/nyc311_", valid_months$year, "_", valid_months$month, ".csv"))
download.file(valid_months$src[[1]], valid_months$lcl[[1]])
```

And I got the following Error and WARNING:

```
downloaded 0 bytes

Error in download.file(valid_months$src[[1]], valid_months$lcl[[1]]) : 
  cannot download all files
In addition: Warning message:
In download.file(valid_months$src[[1]], valid_months$lcl[[1]]) :
  URL 'https://data.cityofnewyork.us/resource/fhrw-4uyv.csv?$where=created_date%20between%20'2011-02-01'%20and%20'2011-02-28'&$limit=100': status was '400 Bad Request'
```

**Comment by liwencong1995** [comment] 2016-11-08 22:00
So, I googled `400 Bad Request`.

And here is what I have found:

The Web server (running the Web site) thinks that the data stream sent by the client (e.g. your Web browser or our CheckUpDown robot) was 'malformed' i.e. did not respect the HTTP protocol completely. So the Web server was unable to understand the request and process it.

It almost always means bad programming of the client system and/or the Web server.

There is a low-level problem in the client or the Web server or both. 95% of the time this is because of a problem on the client system e.g. there is something unstable on your PC running the Web browser.

I am not sure whether it is **my computer's problem or a general problem**. I will test it!

**Comment by liwencong1995** [comment] 2016-11-10 18:45
I have tried it again and got the same `400 Bad Request` error. Can you try it on your computer and see whether you are able to download anything or not?

**Comment by beanumber** [comment] 2016-11-11 18:59
I think the problem is that `downloader::download()` tries to figure out what `method` argument to pass to `download.file()`. But we are trying to explicitly set the `method` argument. 

Note that you can reproduce this:

```
> downloader::download("https://github.com/wch/downloader/zipball/master",
          "downloader.zip", mode = "wb", method = "libcurl")
Error in download.file(url, method = method, ...) : 
  formal argument "method" matched by multiple actual arguments
```

I guess maybe we don't want to use `etl::smart_download()` here after all -- maybe we should appeal directly to `download.file()`. But then that might put us right back to where we were before. I'm not sure how to proceed...

**Comment by liwencong1995** [comment] 2016-12-13 21:08
I just updated the `etl_extract_nyc311` so that it does not use `smart_download` anymore. `etl_extract_nyc311` works just fine now!

**Comment by liwencong1995** [comment] 2016-12-13 21:08
Can I close this issue?

**Comment by beanumber** [comment] 2016-12-14 02:26
It seems to work for me. Have you tested in on Windows?

**Comment by liwencong1995** [comment] 2016-12-14 19:58
Yes, it worked! The `tryCatch` commend was included in `etl_extract` in order to fix the problem on Windows system.

**Comment by beanumber** [comment] 2016-12-14 20:47
Great, sounds like you can close this then.

**Closed as completed** 2016-12-15 01:34 UTC
